# NumPy 和陣列導向的程式設計

`NumPy` 可以說是 Python 中最最標準的科學計算、數據分析套件。也因為 `NumPy` 的出現, 讓 Python 有了非常好的數據分析基礎, 一直到現在成為數據分析覇主。

In [4]:
import numpy as np
a = np.arange(5)
print(a)
b = np.arange(1, 6)
print(b)


[0 1 2 3 4]
[1 2 3 4 5]


In [7]:
import numpy as np
s = 0
grades = [77, 85, 56, 90, 66]
for i in grades:
    s += i
print('平均 = {}' .format(s/len(grades)))

平均 = 74.8


## 1. 陣列導向 101

科學計算一個很核心的概念叫 "array oriented" 的寫法。Array 是 `numpy` 標準的資料結構, 和 list 很像, 但就差了那麼一點點。而這一點點讓我們在計算上是無比的方便。

### 【暖身】 計算平均

某位同學期中考各科成績如下, 請幫他計算成績。

    grades = [77, 85, 56, 90, 66]
    
請計算平均。

In [1]:
# 1. 定義成績列表
grades = [77, 85, 56, 90, 66]

# 2. 計算總分與學科數量
total_score = sum(grades)
number_of_subjects = len(grades)

# 3. 計算平均 (總分 / 數量)
average = total_score / number_of_subjects

# 4. 輸出結果
print(f"總分是：{total_score}")
print(f"平均成績是：{average}")

總分是：374
平均成績是：74.8


### 【示範】陣列導向

In [3]:
import numpy as np
average = np.mean(grades)
print(average)

74.8


最大值

In [4]:
max_val = np.max(grades)
print(max_val)

90


標準差

In [5]:
std_dev = np.std(grades)
print(std_dev)

12.416118556135006


### 【暖身】 換算匯率

假設今天我想查查號稱 Pentax 三公主的 31mm, 43mm, 77mm 三隻 limited 鏡頭在美國賣多少。於是我去 B&H 查了他們的價格分別是:

    prices = [1096.95, 596.95, 896.95]
    
我又查了 Google 匯率 1 美金為 31.71 元。請把三支鏡頭的價格換算為台幣。

In [ ]:
prices = [1096.95, 596.95, 896.95]


先不管這實在有夠醜的數字, 我們要記得在科學計算中:

### 儘可能不要使用迴圈

這可能嗎?

### 【示範】陣列換算匯率

In [6]:
import numpy as np

# 1. 定義美金價格列表並轉換為 NumPy 陣列
prices = np.array([1096.95, 596.95, 896.95])

# 2. 定義匯率
usd_to_twd = 31.71

# 3. 陣列換算匯率 (直接相乘，不需要寫 for 迴圈)
prices_twd = prices * usd_to_twd

# 4. 輸出結果
print(prices_twd)

[34784.2845 18929.2845 28442.2845]


哦哦, 傑克, 這太神奇了!

## 2. 其實 array 還有很多功能

### 【練習】 成績計算

一位老師成績這樣算的:

* 平時成績 20%
* 期中考   35%
* 期未考   45%

有位同學

* 平時成績 85 分
* 期中 70 分
* 期末 80 分

這位同學的學期成績是多少?

In [17]:
grades = np.array([85,70,80])
weights = np.array([0.2, 0.35, 0.45])

這還不是我們要的最終成績啊!

In [7]:
import numpy as np

# 1. 定義成績與權重陣列
grades = np.array([85, 70, 80])
weights = np.array([0.2, 0.35, 0.45])

# 2. 計算加權後的分數 (對應圖片中的 [18] 輸出)
weighted_scores = grades * weights
print(f"加權分數為：{weighted_scores}")

# 3. 計算最終學期總分
# 方法 A：將加權後的陣列加總
final_score_a = weighted_scores.sum()

# 方法 B：直接使用向量內積 (Dot Product)
final_score_b = np.dot(grades, weights)

print(f"最終學期成績是：{final_score_a}")

加權分數為：[17.  24.5 36. ]
最終學期成績是：77.5


### 【提示】 array 還有很多函數可以用

可以先打入

    weighted_grades.
    
先不要按 `enter` 或 `shift-enter`, 而是按 `tab`...


77.5

### 【技巧】 一行完成成績計算

77.5

## 3. 重要的 array 大變身!

我們在數據分析, 常常要改 array 的型式。

### 【練習】 一個 50 個數字的 array

先想辦法、用亂數做出 50 個數字的 array, 叫做 A 好了。

In [9]:
import numpy as np

# 用亂數做出 50 個數字的 array，叫做 A
# np.random.rand(50) 會產生 50 個介於 0 到 1 之間的隨機浮點數
A = np.random.rand(50)
print(A)

[0.53566127 0.52827942 0.9747333  0.9543793  0.24541998 0.62213596
 0.57217274 0.88083417 0.11816211 0.90571419 0.30753137 0.31227448
 0.48063267 0.56460612 0.8455859  0.79802381 0.58725718 0.48335166
 0.0209879  0.59850898 0.24213263 0.12856868 0.24983642 0.14362881
 0.4764439  0.18879748 0.76253742 0.20957714 0.02331051 0.62290372
 0.73525732 0.94322495 0.42157566 0.78979943 0.88193642 0.15079667
 0.56777638 0.19358866 0.79254137 0.58296424 0.80793203 0.50887973
 0.77410901 0.73540554 0.3032745  0.85032347 0.87311204 0.19182421
 0.12833974 0.13746368]


In [10]:
print(A[0])

0.5356612699912812


### 【技巧】 檢查 A 的 `shape`

In [11]:
print(A.shape)

(50,)


### 【技巧】 更改 A 的 shape

In [13]:
A.shape = (5, 10)
print(A[0, 0])

0.5356612699912812


### 【技巧】 也可以用 `reshape`

但要注意, reshape 並沒有改原來的陣列。

In [29]:
import numpy as np

# 假設我們延續前面的 A，是一個包含 50 個數字的一維陣列
A = np.random.rand(50)

# ---
# 【技巧】也可以用 reshape
# ---

# 使用 reshape 改變形狀 (例如改成 10 列 5 欄)
# 注意：reshape 會「回傳」一個新形狀的陣列，但「不會改變」原本 A 的形狀
B = A.reshape(10, 5)

print("B 的形狀:", B.shape) # 輸出 (10, 5)
print("原本 A 的形狀:", A.shape) # 輸出 (50,)，證明 A 沒被改變

# ---
# 【技巧】拉平 ravel
# ---

# 使用 ravel() 將多維陣列「拉平」回一維陣列
# 這比寫 .reshape(50) 看起來更簡潔、更專業（也就是圖片說的「很潮」）
A_flat = B.ravel()

print("拉平後的形狀:", A_flat.shape) # 輸出 (50,)
print(A_flat)

B 的形狀: (10, 5)
原本 A 的形狀: (50,)
拉平後的形狀: (50,)
[0.83905696 0.2895146  0.64661981 0.96215226 0.30653843 0.85884105
 0.5592541  0.41814451 0.59413392 0.62647125 0.87568629 0.63147936
 0.07957602 0.90639094 0.12787787 0.20244215 0.79225864 0.68956163
 0.45226305 0.29197424 0.82156009 0.36492782 0.08411866 0.66149918
 0.8238393  0.79592051 0.51367719 0.00741977 0.86500359 0.1543937
 0.50151599 0.31763398 0.30787654 0.87133188 0.64581971 0.74617777
 0.76690516 0.8902591  0.75100365 0.84235868 0.19416043 0.86805003
 0.41006237 0.50475301 0.45544064 0.90234589 0.83107178 0.21173912
 0.83908759 0.69419663]


### 【技巧】 拉平 `ravel`

雖然你想一想就知道可以用 `shape` 或 `reshape` 把多維陣列拉成一維。不過用 `ravel` 很潮。

array([0.7372234 , 0.6126442 , 0.27626397, 0.28984569, 0.4988311 ,
       0.42021495, 0.4515489 , 0.15328583, 0.93455268, 0.23537373,
       0.24761985, 0.41945762, 0.44871061, 0.66726833, 0.15622678,
       0.70315927, 0.98138833, 0.8233088 , 0.85394749, 0.14797509,
       0.32816167, 0.64607213, 0.96849395, 0.90799427, 0.19579351,
       0.35618479, 0.30311169, 0.32568614, 0.66885309, 0.67844806,
       0.18201376, 0.69592441, 0.11077285, 0.22884185, 0.29488536,
       0.90457337, 0.19872841, 0.38361489, 0.35731267, 0.76200102,
       0.92178147, 0.44190395, 0.07941469, 0.03253205, 0.44805018,
       0.38885104, 0.15473767, 0.55240742, 0.80182196, 0.70921062])

## 4. 快速 array 生成法

### 【技巧】 都是 0 的 array

In [15]:
import numpy as np

# ---
# 1. 【技巧】全部為 0 的陣列 (np.zeros)
# ---

# 產生指定形狀的零陣列
# 傳入 tuple 指定 (列, 欄)。例如 (10, 10)
zeros_array = np.zeros((10, 10))
print(zeros_array)


# ---
# 2. 【技巧】全部為 1 的陣列 (np.ones)
# ---

# 產生指定長度且內容全為 1. 的一維陣列
ones_array = np.ones(10)
print(ones_array)


# ---
# 3. 【技巧】單位矩陣 (np.eye)
# ---

# 產生一個對角線為 1，其餘為 0 的正方形矩陣
# 傳入一個數字 n，會產生 n x n 的單位矩陣
identity_matrix = np.eye(5)
print(identity_matrix)


# ---
# 4. 【技巧】給定範圍均勻生出 n 個點 (np.linspace)
# ---

# 這常用於畫圖時產生 X 軸的座標點
# 例如：從 0 到 10 之間，均勻取出 5 個點
points = np.linspace(0, 10, 5)
print(points) # 輸出會是 [ 0.   2.5  5.   7.5 10. ]

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[ 0.   2.5  5.   7.5 10. ]


### 【技巧】 都是 1 的 array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### 【技巧】單位矩陣

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### 【技巧】給定範圍均勻生出 n 個點

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

### 【技巧】`range` 的 array 版

就是 `arange`。

In [18]:
import numpy as np

# 語法：np.arange(起始值, 結束值, 間隔)
# 注意：結束值 10 是「不包含」在內的
arr = np.arange(1, 10, 0.2)

print(arr)

[1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4 3.6 3.8 4.  4.2 4.4
 4.6 4.8 5.  5.2 5.4 5.6 5.8 6.  6.2 6.4 6.6 6.8 7.  7.2 7.4 7.6 7.8 8.
 8.2 8.4 8.6 8.8 9.  9.2 9.4 9.6 9.8]


## 5. 超重要 `axis` 觀念

初學 `numpy` 很多人有點弄不清楚 `axis` 概念。其實掌握矩陣, 或很像矩陣的陣列都是「先列後行」就可以!

我們先弄個 array 來練習。

In [28]:
import numpy as np

# 建立圖片上半部出現的陣列 (從 1 到 9.8，間隔 0.2)
# 我們可以用 np.arange(開始, 結束, 間隔) 來達成
A = np.arange(1, 10, 0.2)
print("原始長陣列 A 的前五碼：", A[:5])

# ---
# 【重點】一列一列算下來是 axis=0 (垂直方向)
# ---

# 建立圖片中的範例矩陣
B = np.array([[0, 1, 2, 3, 4], 
              [5, 6, 7, 8, 9]])

# 執行 axis=0 的運算 (垂直相加：0+5, 1+6, 2+7...)
sum_0 = B.sum(axis=0)
print("\n[axis=0] 垂直相加的結果：")
print(sum_0) # 輸出：array([ 5,  7,  9, 11, 13])

# ---
# 【重點】一行一行算過去是 axis=1 (水平方向)
# ---

# 執行 axis=1 的運算 (水平相加：0+1+2+3+4, 5+6+7+8+9)
sum_1 = B.sum(axis=1)
print("\n[axis=1] 水平相加的結果：")
print(sum_1) # 輸出：array([10, 35])

# 全部相加結果
print('全部相加結果:' ,sum(A))


原始長陣列 A 的前五碼： [1.  1.2 1.4 1.6 1.8]

[axis=0] 垂直相加的結果：
[ 5  7  9 11 13]

[axis=1] 水平相加的結果：
[10 35]
全部相加結果: 243.0


### 【重點】 一列一列算下來是 `axis=0`

![axis=0](images/axis0.png)

### 【重點】 一行一行算過去是 `axis=1`

![axis=1](images/axis1.png)

array([10, 35])

### 【提示】當然也有可能全部算

In [54]:
A.sum()

45

## 6. array 過濾器

篩出我們要的資料, 這樣的技巧非常重要!

### 【例子】篩出大於 0 的數

我們有個陣列, 想找出大於 0 的數。<br>
L = np.array([3, -2, -1, 5, 7, -3])

In [55]:
L = np.array([3, -2, -1, 5, 7, -3])

我們可以很白痴的自己判斷...<br>
c = np.array([True,False,False,True,True,False])

In [56]:
c = np.array([True,False,False,True,True,False])

這是做啥呢? 我們可以瞬間...

array([3, 5, 7])

除了自己做很白痴, 這看來很厲害!

事實上我們可以叫 `numpy` 做!

array([ True, False, False,  True,  True, False])

這有點強, 我們還可以一次到位!

array([3, 5, 7])

In [30]:
import numpy as np

# 定義原始陣列 L
L = np.array([3, -2, -1, 5, 7, -3])

# ---
# 方法一：手動建立過濾器 (圖片中的「手動判斷」)
# ---

# 手動建立布林陣列 c，對應 L 中大於 0 的位置
c = np.array([True, False, False, True, True, False])

# 使用過濾器取出資料
# 只有對應位置為 True 的元素會被留下來
print("手動篩選結果：", L[c]) 
# 輸出：array([3, 5, 7])


# ---
# 方法二：讓 NumPy 自動做 
# ---

# 直接下判斷式 L > 0
# NumPy 會自動針對每個元素進行比較，回傳一個布林陣列
mask = L > 0
print("NumPy 自動產生的過濾器：", mask)
# 輸出：array([ True, False, False,  True,  True, False])


# ---
# 方法三：終極絕招（一次到位）
# ---

# 直接將判斷式寫在索引的中括號內，這在資料分析中極為常用
final_result = L[L > 0]
print("一次到位的篩選結果：", final_result)
# 輸出：array([3, 5, 7])

手動篩選結果： [3 5 7]
NumPy 自動產生的過濾器： [ True False False  True  True False]
一次到位的篩選結果： [3 5 7]


## 7. 次元切割刀

`numpy` 中 array 的切割法和 list 很像。

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([3, 4, 5, 6])

### 【技巧】2維陣列切法

記得先列後行!

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

要所有的row, 切出行 1-3 位置。

array([[1, 2],
       [6, 7]])

要所有的行col, 切出第 1 列row!

array([5, 6, 7, 8, 9])

In [31]:
import numpy as np

# ---
# 1. 一維陣列切法 (與 Python List 相似)
# ---

# 建立 0 到 9 的陣列
L = np.arange(10)
print("原始陣列 L:", L)

# 切出索引 3 到 6 的數字 (語法是 3:7，因為不包含結尾的 7)
slice_1d = L[3:7]
print("1D 切片結果:", slice_1d) # 輸出: [3 4 5 6]


# ---
# 2. 二維陣列切法 (重點：先列後行)
# ---

# 建立一個 2x5 的二維陣列
A = np.arange(10).reshape(2, 5)
print("\n原始二維陣列 A:\n", A)

# 要所有的列 (row)，切出第 1 到第 3 欄 (col) 之前的資料
# 逗號前面用 ":" 代表「全部都要」
# 逗號後面用 "1:3" 代表索引 1 到 2 (不含 3)
slice_2d_cols = A[:, 1:3]
print("\n[70] 切出所有列的第 1-3 欄位置:\n", slice_2d_cols)
# 輸出: 
# [[1 2]
#  [6 7]]

# 額外練習：要所有的行 (col)，切出第 1 列 (row 索引 0)
first_row = A[0, :]
print("\n切出第 1 列 (所有行):\n", first_row) # 輸出: [0 1 2 3 4]

原始陣列 L: [0 1 2 3 4 5 6 7 8 9]
1D 切片結果: [3 4 5 6]

原始二維陣列 A:
 [[0 1 2 3 4]
 [5 6 7 8 9]]

[70] 切出所有列的第 1-3 欄位置:
 [[1 2]
 [6 7]]

切出第 1 列 (所有行):
 [0 1 2 3 4]


## 8. `NumPy` 的 `zip` 和 `unzip`

之前我們介紹 list 可以用 `zip` 和 `unzip` (其實還是 `zip`) 做到的資料格式變換, 在 array 中怎麼做呢?

![zip and unzip](images/zip.png)

### 【重點】array 的 `zip`

![array zip](images/arrzip.png)

In [72]:
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

array([1, 2, 3, 4, 5, 6, 7, 8])

### 【重點】array 的 `unzip`

這裡其實只需要用到 array 的切割法...

![array zip](images/arrunzip.png)

In [33]:
import numpy as np

# 定義兩個一維陣列 x 與 y
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])

# ---
# 【重點】array 的 zip (資料合併)
# ---

# 使用 np.c_ 將兩個一維陣列「併排」合併成一個二維陣列
# 這會將 x 做為第一欄，y 做為第二欄
z = np.c_[x, y]
print("Zip 後的二維陣列 z:\n", z)
# 輸出會是：
# [[1 5]
#  [2 6]
#  [3 7]
#  [4 8]]

# 像圖片中那樣「拉平」資料
print("\n拉平後的結果:", z.ravel())
# 輸出：[1 2 3 4 5 6 7 8] (注意：這裡的拉平順序視需求而定)


# ---
# 【重點】array 的 unzip (資料拆解)
# ---

# 如圖片所述，拆解其實只需要用到「切片法 (Slicing)」
# 假設我們要從 z 裡面把原本的兩組資料拿出來：

# 取出第 0 欄（原本的 x）
x_back = z[:, 0]

# 取出第 1 欄（原本的 y）
y_back = z[:, 1]

print("\nUnzip 回來的 x:", x_back)
print("Unzip 回來的 y:", y_back)

Zip 後的二維陣列 z:
 [[1 5]
 [2 6]
 [3 7]
 [4 8]]

拉平後的結果: [1 5 2 6 3 7 4 8]

Unzip 回來的 x: [1 2 3 4]
Unzip 回來的 y: [5 6 7 8]
